### ISSUE TITLE
Running adapterhub-cli causes "ImportError: cannot import name 'ADAPTER_CONFIG_MAP' from 'transformers' "

### ISSUE THREAD

**Issue by dainis-boumber** [Adapter-Hub/Hub#52]
How to reproduce:

1) Install `adapterhub-cli` as specified in the README.md
2) Run $ adapterhub-cli in the terminal

Frequency of occurring: 100% 

System: Ubuntu Linux 22.04

Traceback:

Traceback (most recent call last):
  File "/home/dboumber/anaconda3/envs/hfcli/bin/adapter-hub-cli", line 5, in <module>
    from adapter_hub_cli import main
  File "/home/dboumber/anaconda3/envs/hfcli/lib/python3.9/site-packages/adapter_hub_cli/__init__.py", line 5, in <module>
    from .pack import AdapterPackCommand
  File "/home/dboumber/anaconda3/envs/hfcli/lib/python3.9/site-packages/adapter_hub_cli/pack.py", line 13, in <module>
    from transformers import ADAPTER_CONFIG_MAP, WEIGHTS_NAME, AutoModel
ImportError: cannot import name 'ADAPTER_CONFIG_MAP' from 'transformers' (/home/dboumber/anaconda3/envs/hfcli/lib/python3.9/site-packages/transformers/__init__.py)

**Comment by calpt** [comment]
This repository is no longer maintained, please contribute adapters as described in: https://docs.adapterhub.ml/huggingface_hub.html. Thank you!
